# Generated by Django 4.1.7 on 2023-02-23 20:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0009_remove_setting_close_time_remove_setting_open_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand', models.CharField(blank=True, choices=[('Vestel-SEG', 'vestel-seg'), ('Dijitsu', 'dijitsu'), ('Nordmende', 'nordmende'), ('Vestel-Regal', 'vestel-regal'), ('Navitech', 'navitech'), ('AXEN', 'axen'), ('SUNNY-AXEN', 'sunny-axen'), ('WOON', 'woon'), ('INNOLUX', 'innolux'), ('SANYO', 'sanyo'), ('AUO', 'auo'), ('NEXT', 'next'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('GEEPAS', 'geepas'), ('CHIMEI', 'chimei'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Next', 'next'), ('SAMSUNG', 'samsung'), ('SONY', 'sony'), ('ONVO', 'onvo'), ('Panasonic', 'panasonic'), ('-', ''), ('Homstar', 'homstar'), ('Premier', 'premier'), ('LG', 'lg'), ('REGAL', 'regal'), ('Hi-Level', 'hi-level'), ('Osawa', 'osawa'), ('SHARP', 'sharp'), ('YUMATU', 'yumatu'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel', 'vestel'), ('Vestel-ALBA', 'vestel-alba'), ('Profilo', 'profilo'), ('Acer', 'acer'), ('AWOX', 'awox'), ('Hisense', 'hisense'), ('Lifemaxx', 'lifemaxx'), ('ROWELL', 'rowell'), ('SUNNY', 'sunny'), ('PHILIPS', 'philips'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Dreamstar', 'dreamstar'), ('BOE', 'boe'), ('DARFON', 'darfon'), ('Skytech', 'skytech'), ('SEG', 'seg'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo')], max_length=100)),
                ('durum', models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50)),
                ('yeni', models.CharField(blank=True, choices=[('Yeni', 'yeni')], max_length=10)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='photos/products')),
                ('webp', models.ImageField(blank=True, upload_to='webp/products')),
                ('images2', models.ImageField(blank=True, upload_to='photos2/products')),
                ('webp2', models.ImageField(blank=True, upload_to='webp2/products')),
                ('stock', models.IntegerField()),
                ('ekran', models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LCD', 'lcd'), ('LED', 'led'), ('LED-LCD', 'led-lcd')], max_length=10)),
                ('tags', models.TextField(blank=True, max_length=1000)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('sontarih', models.DateTimeField(blank=True, default=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Related_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benzerresimlink', models.CharField(blank=True, max_length=200)),
                ('benzerad', models.CharField(max_length=200)),
                ('benzerlink', models.CharField(max_length=200)),
                ('benzerfiyat', models.IntegerField()),
                ('benzerstok', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'related product',
            },
        ),
    ]
