# Generated by Django 4.1.7 on 2023-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Hi-Level', 'hi-level'), ('Dijitsu', 'dijitsu'), ('Panasonic', 'panasonic'), ('DARFON', 'darfon'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('NEXT', 'next'), ('Dreamstar', 'dreamstar'), ('Hisense', 'hisense'), ('INNOLUX', 'innolux'), ('SUNNY-AXEN', 'sunny-axen'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SHARP', 'sharp'), ('GEEPAS', 'geepas'), ('SANYO', 'sanyo'), ('Nordmende', 'nordmende'), ('AXEN', 'axen'), ('Premier', 'premier'), ('AUO', 'auo'), ('REGAL', 'regal'), ('Vestel', 'vestel'), ('Vestel-ALBA', 'vestel-alba'), ('Navitech', 'navitech'), ('SEG', 'seg'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('-', ''), ('LG', 'lg'), ('SAMSUNG', 'samsung'), ('Osawa', 'osawa'), ('SONY', 'sony'), ('Vestel-SEG', 'vestel-seg'), ('Homstar', 'homstar'), ('Vestel-Regal', 'vestel-regal'), ('Skytech', 'skytech'), ('Lifemaxx', 'lifemaxx'), ('SUNNY', 'sunny'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('WOON', 'woon'), ('Acer', 'acer'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('Profilo', 'profilo'), ('BOE', 'boe'), ('YUMATU', 'yumatu'), ('CHIMEI', 'chimei'), ('AWOX', 'awox'), ('PHILIPS', 'philips'), ('Next', 'next')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
