# Generated by Django 4.1.7 on 2023-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('GEEPAS', 'geepas'), ('Nordmende', 'nordmende'), ('ROWELL', 'rowell'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Premier', 'premier'), ('SEG', 'seg'), ('YUMATU', 'yumatu'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SHARP', 'sharp'), ('Vestel-ALBA', 'vestel-alba'), ('REGAL', 'regal'), ('NEXT', 'next'), ('DARFON', 'darfon'), ('AXEN', 'axen'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Hisense', 'hisense'), ('Dreamstar', 'dreamstar'), ('Vestel', 'vestel'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Skytech', 'skytech'), ('INNOLUX', 'innolux'), ('Hi-Level', 'hi-level'), ('Vestel-Regal', 'vestel-regal'), ('Vestel-SEG', 'vestel-seg'), ('Navitech', 'navitech'), ('SUNNY', 'sunny'), ('LG', 'lg'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SUNNY-AXEN', 'sunny-axen'), ('Homstar', 'homstar'), ('SAMSUNG', 'samsung'), ('Lifemaxx', 'lifemaxx'), ('BOE', 'boe'), ('Dijitsu', 'dijitsu'), ('ONVO', 'onvo'), ('-', ''), ('SANYO', 'sanyo'), ('WOON', 'woon'), ('Next', 'next'), ('PHILIPS', 'philips'), ('Acer', 'acer'), ('Osawa', 'osawa'), ('AWOX', 'awox'), ('SONY', 'sony'), ('Panasonic', 'panasonic'), ('AUO', 'auo'), ('Profilo', 'profilo'), ('CHIMEI', 'chimei')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
