# Generated by Django 4.1.7 on 2023-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('RONAX-TELENOVA', 'ronax-telenova'), ('INNOLUX', 'innolux'), ('SONY', 'sony'), ('SUNNY', 'sunny'), ('Hisense', 'hisense'), ('Premier', 'premier'), ('Panasonic', 'panasonic'), ('REGAL', 'regal'), ('SANYO', 'sanyo'), ('Vestel-SEG', 'vestel-seg'), ('Osawa', 'osawa'), ('Vestel-ALBA', 'vestel-alba'), ('SEG', 'seg'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('SHARP', 'sharp'), ('BOE', 'boe'), ('DARFON', 'darfon'), ('-', ''), ('Hi-Level', 'hi-level'), ('GEEPAS', 'geepas'), ('AXEN', 'axen'), ('Nordmende', 'nordmende'), ('PHILIPS', 'philips'), ('Dijitsu', 'dijitsu'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AUO', 'auo'), ('CHIMEI', 'chimei'), ('LG', 'lg'), ('Lifemaxx', 'lifemaxx'), ('SAMSUNG', 'samsung'), ('Vestel-Regal', 'vestel-regal'), ('Profilo', 'profilo'), ('Homstar', 'homstar'), ('Vestel', 'vestel'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('YUMATU', 'yumatu'), ('Skytech', 'skytech'), ('AWOX', 'awox'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('WOON', 'woon'), ('NEXT', 'next'), ('Next', 'next'), ('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('Navitech', 'navitech'), ('Acer', 'acer'), ('Dreamstar', 'dreamstar'), ('SUNNY-AXEN', 'sunny-axen')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
