# Generated by Django 4.1.7 on 2023-02-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('RONAX-TELENOVA', 'ronax-telenova'), ('ROWELL', 'rowell'), ('SANYO', 'sanyo'), ('SAMSUNG', 'samsung'), ('-', ''), ('AXEN', 'axen'), ('Hisense', 'hisense'), ('YUMATU', 'yumatu'), ('Acer', 'acer'), ('SUNNY', 'sunny'), ('INNOLUX', 'innolux'), ('Lifemaxx', 'lifemaxx'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('LG', 'lg'), ('AWOX', 'awox'), ('PHILIPS', 'philips'), ('WOON', 'woon'), ('Navitech', 'navitech'), ('SUNNY-AXEN', 'sunny-axen'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('REGAL', 'regal'), ('SONY', 'sony'), ('Skytech', 'skytech'), ('Osawa', 'osawa'), ('Vestel-Regal', 'vestel-regal'), ('Nordmende', 'nordmende'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('ONVO', 'onvo'), ('Homstar', 'homstar'), ('Next', 'next'), ('Vestel-ALBA', 'vestel-alba'), ('SEG', 'seg'), ('DARFON', 'darfon'), ('BOE', 'boe'), ('Panasonic', 'panasonic'), ('Hi-Level', 'hi-level'), ('Dreamstar', 'dreamstar'), ('AUO', 'auo'), ('CHIMEI', 'chimei'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('SHARP', 'sharp'), ('GEEPAS', 'geepas'), ('NEXT', 'next'), ('Dijitsu', 'dijitsu'), ('Vestel-SEG', 'vestel-seg'), ('Vestel', 'vestel'), ('Profilo', 'profilo'), ('Premier', 'premier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
