# Generated by Django 4.1.7 on 2023-03-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='related_product',
            name='benzerstok',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SONY', 'sony'), ('Vestel-Nexon', 'vestel-nexon'), ('Dreamstar', 'dreamstar'), ('SAMSUNG', 'samsung'), ('PHILIPS', 'philips'), ('Next', 'next'), ('Lifemaxx', 'lifemaxx'), ('WOON', 'woon'), ('GEEPAS', 'geepas'), ('Hi-Level', 'hi-level'), ('LG', 'lg'), ('Hisense', 'hisense'), ('ROWELL', 'rowell'), ('YUMATU', 'yumatu'), ('CHIMEI', 'chimei'), ('Acer', 'acer'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('SANYO', 'sanyo'), ('SEG', 'seg'), ('Navitech', 'navitech'), ('INNOLUX', 'innolux'), ('BOE', 'boe'), ('Dijitsu', 'dijitsu'), ('REGAL', 'regal'), ('Vestel', 'vestel'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('-', ''), ('Skytech', 'skytech'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('AUO', 'auo'), ('Profilo', 'profilo'), ('Osawa', 'osawa'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel-Regal', 'vestel-regal'), ('Homstar', 'homstar'), ('Vestel-SEG', 'vestel-seg'), ('FSP', 'fsp'), ('Nordmende', 'nordmende'), ('AWOX', 'awox'), ('NEXT', 'next'), ('MEGMEET', 'megmeet'), ('ONVO', 'onvo'), ('Premier', 'premier'), ('DARFON', 'darfon'), ('SUNNY-AXEN', 'sunny-axen'), ('SHARP', 'sharp'), ('RONAX-TELENOVA', 'ronax-telenova'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('AXEN', 'axen'), ('Vestel-ALBA', 'vestel-alba'), ('SUNNY', 'sunny'), ('Panasonic', 'panasonic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='photos2/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='webp',
            field=models.ImageField(blank=True, null=True, upload_to='webp/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='webp2',
            field=models.ImageField(blank=True, null=True, upload_to='webp2/products'),
        ),
    ]
