# Generated by Django 4.1.7 on 2023-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SHARP', 'sharp'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-SEG', 'vestel-seg'), ('FSP', 'fsp'), ('Vestel-Regal', 'vestel-regal'), ('DARFON', 'darfon'), ('Vestel-ALBA', 'vestel-alba'), ('Lifemaxx', 'lifemaxx'), ('Vestel', 'vestel'), ('Panasonic', 'panasonic'), ('PHILIPS', 'philips'), ('Nordmende', 'nordmende'), ('-', ''), ('Homstar', 'homstar'), ('RONAX-TELENOVA', 'ronax-telenova'), ('AUO', 'auo'), ('LG', 'lg'), ('Next', 'next'), ('YUMATU', 'yumatu'), ('Navitech', 'navitech'), ('SANYO', 'sanyo'), ('MEGMEET', 'megmeet'), ('CHIMEI', 'chimei'), ('INNOLUX', 'innolux'), ('REGAL', 'regal'), ('Hi-Level', 'hi-level'), ('SONY', 'sony'), ('Vestel-Nexon', 'vestel-nexon'), ('WOON', 'woon'), ('NEXT', 'next'), ('Skytech', 'skytech'), ('SUNNY-AXEN', 'sunny-axen'), ('Premier', 'premier'), ('AWOX', 'awox'), ('GEEPAS', 'geepas'), ('Acer', 'acer'), ('Osawa', 'osawa'), ('ONVO', 'onvo'), ('Dreamstar', 'dreamstar'), ('Profilo', 'profilo'), ('SEG', 'seg'), ('BOE', 'boe'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Hisense', 'hisense'), ('AXEN', 'axen'), ('SUNNY', 'sunny'), ('SAMSUNG', 'samsung'), ('Dijitsu', 'dijitsu'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('ROWELL', 'rowell'), ('Vestel, Hi-Level', 'vestel,hi-level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd')], max_length=10),
        ),
    ]
