# Generated by Django 4.1.7 on 2023-03-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Vestel, Hi-Level', 'vestel,hi-level'), ('SUNNY', 'sunny'), ('Navitech', 'navitech'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-Nexon', 'vestel-nexon'), ('SHARP', 'sharp'), ('SAMSUNG', 'samsung'), ('RONAX-TELENOVA', 'ronax-telenova'), ('NEXT', 'next'), ('Nordmende', 'nordmende'), ('LG', 'lg'), ('Lifemaxx', 'lifemaxx'), ('FSP', 'fsp'), ('Premier', 'premier'), ('BOE', 'boe'), ('SANYO', 'sanyo'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Vestel-SEG', 'vestel-seg'), ('Dijitsu', 'dijitsu'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('YUMATU', 'yumatu'), ('AUO', 'auo'), ('INNOLUX', 'innolux'), ('Hi-Level', 'hi-level'), ('Vestel-ALBA', 'vestel-alba'), ('PHILIPS', 'philips'), ('-', ''), ('AXEN', 'axen'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Acer', 'acer'), ('Dreamstar', 'dreamstar'), ('MEGMEET', 'megmeet'), ('REGAL', 'regal'), ('SEG', 'seg'), ('SONY', 'sony'), ('SUNNY-AXEN', 'sunny-axen'), ('Homstar', 'homstar'), ('Skytech', 'skytech'), ('ONVO', 'onvo'), ('ROWELL', 'rowell'), ('Vestel', 'vestel'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('DARFON', 'darfon'), ('CHIMEI', 'chimei'), ('Vestel-Regal', 'vestel-regal'), ('Osawa', 'osawa'), ('AWOX', 'awox'), ('Next', 'next'), ('Hisense', 'hisense'), ('Profilo', 'profilo'), ('WOON', 'woon'), ('Panasonic', 'panasonic'), ('GEEPAS', 'geepas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led')], max_length=10),
        ),
    ]
