# Generated by Django 4.1.7 on 2023-03-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('Profilo', 'profilo'), ('SUNNY', 'sunny'), ('WOON', 'woon'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('ONVO', 'onvo'), ('Nordmende', 'nordmende'), ('AUO', 'auo'), ('Vestel-Regal', 'vestel-regal'), ('Arçelik-Beko-Grundig', 'arçelik-beko-grundig'), ('Dreamstar', 'dreamstar'), ('Next', 'next'), ('Panasonic', 'panasonic'), ('-', ''), ('PHILIPS', 'philips'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('MEGMEET', 'megmeet'), ('Navitech', 'navitech'), ('Vestel', 'vestel'), ('SAMSUNG', 'samsung'), ('Vestel-Nexon', 'vestel-nexon'), ('Premier', 'premier'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Homstar', 'homstar'), ('LG', 'lg'), ('CHIMEI', 'chimei'), ('GEEPAS', 'geepas'), ('FSP', 'fsp'), ('Vestel-SEG', 'vestel-seg'), ('Acer', 'acer'), ('ROWELL', 'rowell'), ('SUNNY-AXEN', 'sunny-axen'), ('Hisense', 'hisense'), ('REGAL', 'regal'), ('Dijitsu', 'dijitsu'), ('AWOX', 'awox'), ('BOE', 'boe'), ('Osawa', 'osawa'), ('INNOLUX', 'innolux'), ('SEG', 'seg'), ('Hi-Level', 'hi-level'), ('Vestel-ALBA', 'vestel-alba'), ('RONAX-TELENOVA', 'ronax-telenova'), ('YUMATU', 'yumatu'), ('SONY', 'sony'), ('AXEN', 'axen'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Skytech', 'skytech'), ('SHARP', 'sharp'), ('NEXT', 'next'), ('SANYO', 'sanyo'), ('DARFON', 'darfon'), ('Lifemaxx', 'lifemaxx')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sontarih',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
