# Generated by Django 4.1.7 on 2023-03-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('LG', 'LG'), ('Vestel-SEG', 'vestel-seg'), ('BOE', 'boe'), ('Premier', 'premier'), ('Vestel-Regal', 'vestel-regal'), ('Osawa', 'osawa'), ('Vestel-Toshiba-Profilo', 'vestel-toshiba-profilo'), ('Skytech', 'skytech'), ('GEEPAS', 'geepas'), ('Homstar', 'homstar'), ('AXEN', 'axen'), ('YUMATU', 'yumatu'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('AWOX', 'Awox'), ('WOON', 'Woon'), ('REGAL', 'regal'), ('SAMSUNG', 'Samsung'), ('Navitech', 'navitech'), ('ONVO', 'onvo'), ('RONAX-TELENOVA', 'ronax-telenova'), ('SONY', 'Sony'), ('DARFON', 'darfon'), ('Vestel-ALBA', 'vestel-alba'), ('ROWELL', 'rowell'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Profilo', 'profilo'), ('Dreamstar', 'dreamstar'), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('PHILIPS', 'philips'), ('Next', 'next'), ('Vestel-Nexon', 'vestel-nexon'), ('Panasonic', 'panasonic'), ('FSP', 'fsp'), ('Acer', 'acer'), ('Hi-Level', 'hi-level'), ('SUNNY-AXEN-WOON', 'Sunny-Axen-Woon'), ('-', ''), ('Hisense', 'hisense'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('SHARP', 'sharp'), ('SEG', 'seg'), ('SUNNY', 'Sunny'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('INNOLUX', 'innolux'), ('NEXT', 'next'), ('MEGMEET', 'megmeet'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('AUO', 'Auo'), ('VESTEL', 'Vestel'), ('Lifemaxx', 'lifemaxx'), ('DIJITSU', 'Dijitsu'), ('CHIMEI', 'Chimei')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('Sıfır', '0'), ('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED', 'led'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
