# Generated by Django 4.1.8 on 2023-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_views_count_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TOSHIBA', 'Toshiba'), ('Homstar', 'homstar'), ('SUNNY', 'Sunny'), ('NEMU', 'Nemu'), ('ROWELL', 'Rowell'), ('Vestel-Regal', 'vestel-regal'), ('ONVO-SABA', 'Onvo-Saba'), ('Profilo', 'Profilo'), ('SEG', 'seg'), ('Panasonic', 'Panasonic'), ('LG', 'LG'), ('Hi-Level', 'Hi-Level'), ('DIJITSU', 'Dijitsu'), ('Vestel-Nexon', 'vestel-nexon'), ('AUO', 'Auo'), ('Lifemaxx', 'lifemaxx'), ('SONY', 'Sony'), ('Skytech', 'Skytech'), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('BOE', 'BOE'), ('SHARP', 'Sharp'), ('AFTRON', 'Aftron'), ('Osawa', 'osawa'), ('Navitech', 'Navitech'), ('Vestel-SEG', 'vestel-seg'), ('Premier', 'Premier'), ('VESTEL', 'Vestel'), ('DARFON', 'Darfon'), ('CHIMEI-INNOLUX', 'Chimei-Innolux'), ('Dreamstar', 'dreamstar'), ('PANDA', 'Panda'), ('Haier', 'Haier'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Vestel-ALBA', 'vestel-alba'), ('-', ''), ('YUMATU', 'Yumatu'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('GEEPAS', 'geepas'), ('REGAL', 'regal'), ('WDX', 'WDX'), ('AWOX', 'Awox'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('AXEN', 'axen'), ('FSP', 'fsp'), ('MEGMEET', 'megmeet'), ('WOON', 'Woon'), ('Hisense', 'Hisense'), ('Vestel-Toshiba', 'vestel-toshiba'), ('SAMSUNG', 'Samsung'), ('FISHER', 'Fisher'), ('Acer', 'acer'), ('Next', 'Next'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('TELENOVA-RONAX', 'Telenova-Ronax'), ('PHILIPS', 'Philips'), ('Vestel, Hi-Level', 'vestel,hi-level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2'), ('Sıfır', '0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED', 'led'), ('LED-LCD', 'led-lcd'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
