# Generated by Django 4.1.9 on 2023-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_brand_alter_product_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('Panasonic', 'Panasonic'), ('REGAL', 'regal'), ('PANDA', 'Panda'), ('VESTEL-SEG-REGAL', 'vestel-seg-regal'), ('Vestel-ALBA', 'vestel-alba'), ('-', ''), ('CHIMEI-INNOLUX', 'Chimei-Innolux'), ('Vestel-Nexon', 'vestel-nexon'), ('YUMATU', 'Yumatu'), ('FISHER', 'Fisher'), ('Skytech', 'Skytech'), ('AWOX', 'Awox'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('SUNNY', 'Sunny'), ('Profilo', 'Profilo'), ('Arçelik-Beko-Grundig-Altus', 'arcelik-beko-grundig-altus'), ('Hi-Level', 'Hi-Level'), ('Vestel-Techwood-Regal', 'vestel-techwood-regal'), ('Acer', 'acer'), ('ROWELL', 'Rowell'), ('TELENOVA-RONAX', 'Telenova-Ronax'), ('AUO', 'Auo'), ('Lifemaxx', 'lifemaxx'), ('Navitech', 'Navitech'), ('DARFON', 'Darfon'), ('Vestel-Regal', 'vestel-regal'), ('WOON', 'Woon'), ('MEGMEET', 'megmeet'), ('AFTRON', 'Aftron'), ('Vestel, Hi-Level', 'vestel,hi-level'), ('AXEN', 'axen'), ('Next', 'Next'), ('SHARP', 'Sharp'), ('FSP', 'fsp'), ('BOE', 'BOE'), ('NEMU', 'Nemu'), ('Vestel-Toshiba', 'vestel-toshiba'), ('TOSHIBA', 'Toshiba'), ('PHILIPS', 'Philips'), ('GEEPAS', 'geepas'), ('VESTEL', 'Vestel'), ('Osawa', 'osawa'), ('SEG', 'seg'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('Haier', 'Haier'), ('WDX', 'WDX'), ('ONVO-SABA', 'Onvo-Saba'), ('Hisense', 'Hisense'), ('Homstar', 'homstar'), ('SONY', 'Sony'), ('DIJITSU', 'Dijitsu'), ('Premier', 'Premier'), ('SAMSUNG', 'Samsung'), ('LG', 'LG'), ('Dreamstar', 'dreamstar'), ('Vestel-SEG', 'vestel-seg')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LED-LCD', 'led-lcd'), ('LED', 'led'), ('LCD', 'lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
