# Generated by Django 4.1.9 on 2023-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_brand_alter_product_ekran'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='photos3/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='webp3',
            field=models.ImageField(blank=True, null=True, upload_to='webp3/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('AFTRON', 'Aftron'), ('Hisense', 'Hisense'), ('WDX', 'WDX'), ('SUNNY', 'Sunny'), ('PHILIPS', 'Philips'), ('DARFON', 'Darfon'), ('Acer', 'Acer'), ('TELENOVA-RONAX', 'Telenova-Ronax'), ('Dreamstar', 'dreamstar'), ('WOON', 'Woon'), ('AWOX', 'Awox'), ('-', ''), ('SHARP', 'Sharp'), ('LG', 'LG'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('Hi-Level', 'Hi-Level'), ('TOSHIBA', 'Toshiba'), ('Lifemaxx', 'lifemaxx'), ('Haier', 'Haier'), ('Next', 'Next'), ('Premier', 'Premier'), ('Navitech', 'Navitech'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('CHIMEI-INNOLUX', 'Chimei-Innolux'), ('ROWELL', 'Rowell'), ('SAMSUNG', 'Samsung'), ('Skytech', 'Skytech'), ('Panasonic', 'Panasonic'), ('SONY', 'Sony'), ('ONVO-SABA', 'Onvo-Saba'), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('YUMATU', 'Yumatu'), ('DIJITSU', 'Dijitsu'), ('VESTEL', 'Vestel'), ('PANDA', 'Panda'), ('FISHER', 'Fisher'), ('BOE', 'BOE'), ('Profilo', 'Profilo'), ('NEMU', 'Nemu'), ('AUO', 'Auo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durum',
            field=models.CharField(blank=True, choices=[('2.EL', '2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LCD', 'lcd'), ('LED-LCD', 'led-lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
