# Generated by Django 4.1.9 on 2023-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_images3_product_webp3_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='photos4/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='webp4',
            field=models.ImageField(blank=True, null=True, upload_to='webp4/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('TELENOVA-RONAX', 'Telenova-Ronax'), ('ONVO-SABA', 'Onvo-Saba'), ('-', ''), ('AFTRON', 'Aftron'), ('Skytech', 'Skytech'), ('Lifemaxx', 'lifemaxx'), ('PANDA', 'Panda'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('BOE', 'BOE'), ('Haier', 'Haier'), ('ROWELL', 'Rowell'), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('Profilo', 'Profilo'), ('AUO', 'Auo'), ('SUNNY', 'Sunny'), ('AWOX', 'Awox'), ('Acer', 'Acer'), ('WDX', 'WDX'), ('Premier', 'Premier'), ('NEMU', 'Nemu'), ('WOON', 'Woon'), ('FISHER', 'Fisher'), ('SONY', 'Sony'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('DIJITSU', 'Dijitsu'), ('TOSHIBA', 'Toshiba'), ('Next', 'Next'), ('VESTEL', 'Vestel'), ('SAMSUNG', 'Samsung'), ('Panasonic', 'Panasonic'), ('Hi-Level', 'Hi-Level'), ('LG', 'LG'), ('SHARP', 'Sharp'), ('PHILIPS', 'Philips'), ('DARFON', 'Darfon'), ('Navitech', 'Navitech'), ('Dreamstar', 'dreamstar'), ('YUMATU', 'Yumatu'), ('Hisense', 'Hisense'), ('CHIMEI-INNOLUX', 'Chimei-Innolux')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('LED', 'led'), ('LED-LCD', 'led-lcd'), ('Plazma', 'plazma')], max_length=10),
        ),
    ]
