# Generated by Django 4.1.9 on 2023-06-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_images4_product_webp4_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images5',
            field=models.ImageField(blank=True, null=True, upload_to='photos5/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='webp5',
            field=models.ImageField(blank=True, null=True, upload_to='webp5/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('SONY', 'Sony'), ('LG', 'LG'), ('Next', 'Next'), ('PANDA', 'Panda'), ('Acer', 'Acer'), ('ROWELL', 'Rowell'), ('Profilo', 'Profilo'), ('Navitech', 'Navitech'), ('SAMSUNG', 'Samsung'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('YUMATU', 'Yumatu'), ('AFTRON', 'Aftron'), ('Panasonic', 'Panasonic'), ('Skytech', 'Skytech'), ('Hisense', 'Hisense'), ('PHILIPS', 'Philips'), ('AWOX', 'Awox'), ('TOSHIBA', 'Toshiba'), ('Lifemaxx', 'lifemaxx'), ('FISHER', 'Fisher'), ('CHIMEI-INNOLUX', 'Chimei-Innolux'), ('Premier', 'Premier'), ('NEMU', 'Nemu'), ('Haier', 'Haier'), ('DARFON', 'Darfon'), ('AUO', 'Auo'), ('Hi-Level', 'Hi-Level'), ('-', ''), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('ONVO-SABA', 'Onvo-Saba'), ('TELENOVA-RONAX', 'Telenova-Ronax'), ('WOON', 'Woon'), ('BOE', 'BOE'), ('Dreamstar', 'dreamstar'), ('WDX', 'WDX'), ('SHARP', 'Sharp'), ('SUNNY', 'Sunny'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('VESTEL', 'Vestel'), ('DIJITSU', 'Dijitsu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('Plazma', 'plazma'), ('LCD', 'lcd'), ('LED', 'led'), ('LED-LCD', 'led-lcd')], max_length=10),
        ),
    ]
