# Generated by Django 4.1.9 on 2023-07-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_images5_product_webp5_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images6',
            field=models.ImageField(blank=True, null=True, upload_to='photos6/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='webp6',
            field=models.ImageField(blank=True, null=True, upload_to='webp6/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('ONVO-SABA', 'Onvo-Saba'), ('DIJITSU', 'Dijitsu'), ('SUNNY', 'Sunny'), ('YUMATU', 'Yumatu'), ('SONY', 'Sony'), ('DARFON', 'Darfon'), ('SANYO-NORDMENDE', 'Sanyo-Nordmende'), ('ROWELL', 'Rowell'), ('Haier', 'Haier'), ('VESTEL', 'Vestel'), ('PANDA', 'Panda'), ('Profilo', 'Profilo'), ('SAMSUNG', 'Samsung'), ('WOON', 'Woon'), ('WDX', 'WDX'), ('NEMU', 'Nemu'), ('Navitech', 'Navitech'), ('CHIMEI-INNOLUX', 'Chimei-Innolux'), ('FISHER', 'Fisher'), ('PHILIPS', 'Philips'), ('Arçelik-Beko-Grundig', 'Arçelik-Beko-Grundig'), ('Skytech', 'Skytech'), ('SHARP', 'Sharp'), ('Exper', 'Exper'), ('Hi-Level', 'Hi-Level'), ('TELENOVA-RONAX', 'Telenova-Ronax'), ('AWOX', 'Awox'), ('Acer', 'Acer'), ('AUO', 'Auo'), ('Premier', 'Premier'), ('Panasonic', 'Panasonic'), ('LG', 'LG'), ('SUNNY-AXEN-WOON-SHEEN', 'Sunny-Axen-Woon-Sheen'), ('Dreamstar', 'dreamstar'), ('TOSHIBA', 'Toshiba'), ('Hisense', 'Hisense'), ('Casper', 'Casper'), ('BOE', 'BOE'), ('Next', 'Next'), ('-', ''), ('Lifemaxx', 'lifemaxx'), ('AFTRON', 'Aftron')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ekran',
            field=models.CharField(blank=True, choices=[('LCD', 'lcd'), ('Plazma', 'plazma'), ('LED-LCD', 'led-lcd'), ('LED', 'led')], max_length=10),
        ),
    ]
