# Generated by Django 4.1.1 on 2022-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='keywords',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
