# Generated by Django 4.1.1 on 2022-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_setting_description_alter_setting_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
