# Generated by Django 4.1.3 on 2022-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_setting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='adres',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
