# Generated by Django 4.1.3 on 2022-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_setting_saat'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
