# Generated by Django 4.1.3 on 2023-02-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_setting_close_time_setting_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='open_time',
        ),
    ]
